#---------------------------------------
# include/Makefile.am for BNCmatmul
# Copyright (c) 2014-2026 Tomonori Kouya
#---------------------------------------

AUTOMAKE_OPTIONS = foreign

#---------------------------------------
# Public top-level headers (installed to $(includedir))
#---------------------------------------
nobase_include_HEADERS = \
	_bncomp_linear_cdd.h \
	_bncomp_linear_cqd.h \
	_bncomp_linear_ctd.h \
	benchmark_tools.h \
	bmatrix.h \
	bnc.h bnc_common.h bnc_common_def.h \
	bncmatmul.h bncmm.h bncmm_c.h \
	bncomp.h bncsparse.h bncuda.h \
	bncelem.h bncelem_tables.h bncelem_vector.h rdtq_func.h \
	bncelem_dd.h bncelem_td.h bncelem_qd.h bncelem_f.h \
	bncfma.h bncfma_d.h bncfma_f.h \
	cddlinear.h cdlinear.h \
	cdslinear.h ctslinear.h cqslinear.h \
	clinear.h \
	cmpflinear.h cmpflinear_cu.h cqdlinear.h ctdlinear.h \
	ddlinear.h dlinear.h dslinear.h \
	flinear.h float128linear.h \
	gddlinear.h gdslinear.h \
	gtdlinear.h gtslinear.h \
	gqslinear.h \
	gcdlinear.h gcdsparse.h gcflinear.h gcfsparse.h \
	gdlinear.h gdsparse.h gdssparse.h gddsparse.h \
	gflinear.h gfsparse.h \
	gqdsparse.h gqssparse.h gtdsparse.h gtssparse.h \
	cgddlinear.h cgddsparse.h cgdslinear.h cgdssparse.h \
	cgqdlinear.h cgqdsparse.h cgqslinear.h cgqssparse.h \
	cgtdlinear.h cgtdsparse.h cgtslinear.h cgtssparse.h \
	get_linear_system.h get_secv.h \
	gtestmat.h \
	ieee_floats.h \
	lu_bench.h \
	matmul_strassen.h \
	mmio.h \
	mpf_func_mpfr.h \
	mpflinear.h mpflinear_cu.h \
	mpfr_dd.h \
	mpfr_dtq_sd.h \
	mpi_bnc.h mpi_gmp.h \
	oz_scheme.h \
	poly.h \
	qdlinear.h qslinear.h \
	rcdd.h rcds.h rdd.h rds.h \
	sort.h \
	tdlinear.h \
	template_linear.h \
	tslinear.h \
	avx2/_bncavx_cd.h \
	avx2/_bncavx_cdd.h \
	avx2/_bncavx_cdd_avx512.h \
	avx2/_bncavx_cqd.h \
	avx2/_bncavx_cqd_avx512.h \
	avx2/_bncavx_ctd.h \
	avx2/_bncavx_ctd_avx512.h \
	avx2/_bncavx_d.h \
	avx2/_bncavx_dd.h \
	avx2/_bncavx_dd_avx512.h \
	avx2/_bncavx_deft.h \
	avx2/_bncavx_deft_avx512.h \
	avx2/_bncavx_ds.h \
	avx2/_bncavx_ds_avx512.h \
	avx2/_bncavx_f.h \
	avx2/_bncavx_feft.h \
	avx2/_bncavx_feft_avx512.h \
	avx2/_bncavx_fma.h \
	avx2/_bncavx_qd.h \
	avx2/_bncavx_qd_avx512.h \
	avx2/_bncavx_qs.h \
	avx2/_bncavx_qs_avx512.h \
	avx2/_bncavx_td.h \
	avx2/_bncavx_td_avx512.h \
	avx2/_bncavx_ts.h \
	avx2/_bncavx_ts_avx512.h \
	avx2/bncavx.h \
	neon/_bncneon128_qd.h \
	neon/_bncneon_cd.h \
	neon/_bncneon_cd_old.h \
	neon/_bncneon_cdd.h \
	neon/_bncneon_cqd.h \
	neon/_bncneon_ctd.h \
	neon/_bncneon_d.h \
	neon/_bncneon_dd.h \
	neon/_bncneon_deft.h \
	neon/_bncneon_ds.h \
	neon/_bncneon_feft.h \
	neon/_bncneon_fma.h \
	neon/_bncneon_qd.h \
	neon/_bncneon_qs.h \
	neon/_bncneon_td.h \
	neon/_bncneon_ts.h \
	neon/bncneon.h \
	sve2/_bncsve2_cdd.h \
	sve2/_bncsve2_ctd.h \
	sve2/_bncsve2_cqd.h \
	sve2/_bncsve2_d.h \
	sve2/_bncsve2_dd.h \
	sve2/_bncsve2_deft.h \
	sve2/_bncsve2_ds.h \
	sve2/_bncsve2_feft.h \
	sve2/_bncsve2_fma.h \
	sve2/_bncsve2_qd.h \
	sve2/_bncsve2_qs.h \
	sve2/_bncsve2_td.h \
	sve2/_bncsve2_ts.h \
	sve2/bncsve2.h
